### ISSUE TITLE
invalid charts rendering when value is constant and yRangePad = 1

### ISSUE THREAD

**Issue by ktsaou** [danvk/dygraphs#781]
Hi,

Using the latest git version, when there is a chart with a **constant non-zero value**, the chart is not rendered properly.

The following images come from the same browser, same application, but different dygraph versions.

On the left the git version f6ec7be9627c2dc74776a027349c58f956a99621 and on the right the latest release:

**Note that the git version does not show the y-axis labels at all. It is like the chart is rendered below the visible area.**

![image](https://cloud.githubusercontent.com/assets/2662304/18971560/1cb55c4c-869e-11e6-850a-ccf869beb411.png)

![image](https://cloud.githubusercontent.com/assets/2662304/18971590/394d7f7e-869e-11e6-8c0a-fe9f9fb52469.png)

![image](https://cloud.githubusercontent.com/assets/2662304/18971658/7c0926f6-869e-11e6-9f8a-81bf148ff804.png)

**Comment by danvk** [comment]
I merged in a major change yesterday which requires you to source a CSS file to get a proper rendering. Maybe you're running into that?
https://github.com/danvk/dygraphs/pull/678

**Comment by ktsaou** [comment]
I am reading now (I see I use the killed options). I'll use the new ones and come back.
Keep in mind I made the same test 2 weeks ago, and had the same result.

**Comment by danvk** [comment]
OK. If you do still see the issue, please provide a self-contained repro. There are _many_ charts in `tests/` which do not appear broken.

**Comment by ktsaou** [comment]
Yeap, I included `dygraph.css`, the problem remains. I will try to make a test for it.

**Comment by ktsaou** [comment]
Found it.

The problem is `yRangePad: 1`.
If I remove this, it works.

Here is a test:

```html
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="../css/dygraph.css">
    <title>dygraph</title>
    For production (minified) code, use:
    <script type="text/javascript" src="../dist/dygraph-combined.js"></script>
    <script type="text/javascript" src="../src/extras/smooth-plotter.js"></script>
    <!--
    <script type="text/javascript" src="../dist/dygraph.js"></script>
    -->

  </head>
  <body>
    <p>Minimal example of a dygraph chart:</p>
    <div id="graphdiv"></div>
    <script type="text/javascript">
      g = new Dygraph(document.getElementById("graphdiv"),
                      "Date,Temperature\n" +
                      "2008-05-07,10\n" +
                      "2008-05-08,10\n" +
                      "2008-05-09,10\n");
    </script>

    <p>Same data, specified in a parsed format:</p>
    <div id="graphdiv2"></div>
    <script type="text/javascript">
      g2 = new Dygraph(document.getElementById("graphdiv2"),
                       [ [ new Date("2008/05/07"), 10],
                         [ new Date("2008/05/08"), 10],
                         [ new Date("2008/05/08"), 10],
                         [ new Date("2008/05/10"), 10],
                         [ new Date("2008/05/11"), 10],
                         [ new Date("2008/05/12"), 10],
                         [ new Date("2008/05/13"), 10],
                         [ new Date("2008/05/14"), 10],
                         [ new Date("2008/05/15"), 10],
                         [ new Date("2008/05/16"), 10],
                         [ new Date("2008/05/17"), 10],
                         [ new Date("2008/05/18"), 10],
                         [ new Date("2008/05/19"), 10],
                         [ new Date("2008/05/20"), 10],
                         [ new Date("2008/05/21"), 10]
                       ],
                       {
                          rightGap: 5,
                          showRangeSelector: false,
                          showRoller: false,
                          title: 'hello world',
                          titleHeight: 19,
                          legend: 'always',
                          labelsSeparateLines: true,
                          labelsShowZeroValues: true,
                          labelsKMB: false,
                          labelsKMG2: false,
                          showLabelsOnHighlight: true,
                          hideOverlayOnMouseOut: true,
                          includeZero: false,
                          xRangePad: 0,
                          yRangePad: 1,
                          valueRange: null,
                          ylabel: 'percent',
                          labels: [ "Date", "Temperature" ]
                       });
    </script>
  </body>
</html>
```

**Comment by ktsaou** [comment]
image: 
![image](https://cloud.githubusercontent.com/assets/2662304/18972837/67a22686-86a3-11e6-9bc7-b3f5fc424a1f.png)

**Comment by ktsaou** [comment]
I used that option because on a few charts the minimum value was clipped by 1 pixel (I also use smooth plotter if that matters). With this option I prevented that tiny clipping.

**Comment by danvk** [comment]
Could you try to figure out which commit broke this? There have been very few in the last two weeks.

**Comment by ktsaou** [comment]
I am not sure this happened in the last 2 weeks. The version I used that does not have this problem is the released one (v1.1.1). It might be something committed a year ago...

**Comment by danvk** [comment]
I can confirm that this regressed from 1.1.1 to HEAD.

**Comment by danvk** [comment]
I ran `git bisect` with your example and found the culprit: #732 

@klausw hope you're doing well! Any ideas why this broke? I'd like to fix this before cutting the 2.0.0 release candidate.

**Comment by klausw** [comment]
I think I can see the issue. The if (!axis.valueWindow && !ypadCompat) path doesn't currently have the special case for span == 0 that's used in non-padding mode, so the Y axis ends up with equal top and bottom values which doesn't render right.

I don't currently have time to do a proper patch, but roughly something like this should work:

     if (!axis.valueWindow && !ypadCompat) {
       // When using yRangePad, adjust the upper/lower bounds to add
       // padding unless the user has zoomed/panned the Y axis range.
       if (logscale) {
         y0 = axis.computedValueRange[0];
         y1 = axis.computedValueRange[1];
         var y0pct = ypad / (2 * ypad - 1);
         var y1pct = (ypad - 1) / (2 * ypad - 1);
         axis.computedValueRange[0] = utils.logRangeFraction(y0, y1, y0pct);
         axis.computedValueRange[1] = utils.logRangeFraction(y0, y1, y1pct);
       } else {
         y0 = axis.computedValueRange[0];
         y1 = axis.computedValueRange[1];
         span = y1 - y0;

.... add this
      // special case: if we have no sense of scale, center on the sole value.
       if (span === 0) {
         if (y1 !== 0) {
           span = Math.abs(y1);
         } else {
           // ... and if the sole value is zero, use range 0-1.
           y1 = 1;
           span = 1;
          }
        }
... to here

         axis.computedValueRange[0] = y0 - span * ypad;
         axis.computedValueRange[1] = y1 + span * ypad;
       }
     }

The logscale branch may need something similar, not sure what expected behavior is there.

**Comment by ktsaou** [comment]
I make PR #909 that fixes this.

**Comment by mirabilos** [comment]
PR was merged
